### ISSUE TITLE
Suggestion: Add a [noWaitTimeForLock] flag for AcquireLockOptions

### ISSUE THREAD

**Issue by padum60** [awslabs/dynamodb-lock-client#12]
It would be useful to have to possibly to try to acquire a lock without having to wait a full **LEASE_DURATION**.

https://github.com/awslabs/dynamodb-lock-client/blob/e44962dcb08d51f134a42c9e36fbd424cfb781c2/src/main/java/com/amazonaws/services/dynamodbv2/AmazonDynamoDBLockClient.java#L443

Currently we are bypassing this behaviour by adding a negative time for `withAdditionalTimeToWaitForLock`. This is not so clean, that's why having a boolean flag `noWaitTimeForLock` for `AcquireLockOptions` that subtract the `lease_duration` from `millisecondsToWait` would be a nice feature.

**Comment by JohntaviousB** [comment]
Seconded

**Comment by amcp** [comment]
@padum60 Very good suggestion. Would skipping the initial blocking wait with a boolean flag in AcquireLockOptions suffice?

**Comment by padum60** [comment]
First of all, thanks for your reply.

Yes, if we are talking about skipping this block :
```
 if (!alreadySleptOnceForOneLeasePeriod) {
     alreadySleptOnceForOneLeasePeriod = true;
     millisecondsToWait += existingLock.get().getLeaseDuration();
}
```
it should be enough.

I was wondering if it was intended that `AcquireLockOptions.withAdditionalTimeToWaitForLock` could have a negative value. With the implementation of the new flag, maybe `withAdditionalTimeToWaitForLock` could enforce a positive wait time as the name of the flag suggest.
